In [ ]:
#Linear Regression

In [ ]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

X = housing.data
y = housing.target

print(X.shape)
print(y.shape)

(20640, 8)
(20640,)

In [ ]:
import sklearn
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df=fetch_california_housing()

In [ ]:

print(housing.feature_names[0:])

['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg=LinearRegression()
n_mse=cross_val_score(lin_reg,X,y,scoring = 'neg_mean_squared_error',cv=5)
print(n_mse)
mean_n_mse=np.mean(n_mse)
print(mean_n_mse)

# mse ki value small aati h but it wants it big hence it multiplies by -1 to make number seem bigger

ValueError: Found input variables with inconsistent numbers of samples: [569, 20640]

On average, across 5 different train-test splits, your model explains about 83.6% of the variation in the target variable.

Higher is better for R².

In [ ]:
lin_reg.predict(X)

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

ValueError: X has 30 features, but LinearRegression is expecting 8 features as input.

In [ ]:
# Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge=Ridge()

params={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20]}

ridge_regressor=GridSearchCV(ridge,params,scoring='neg_mean_squared_error',cv=5)
ridge_regressor.fit(X,y)

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [ ]:
print(ridge_regressor.best_score_)      #here value of best score increased comp to linear hence dont use it
print(ridge_regressor.best_params_)

-0.558102003562591
{'alpha': 20}

In [ ]:
# Lasso Regression
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
lasso=Lasso()

params={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20]}

lasso_regressor=GridSearchCV(lasso,params,scoring='neg_mean_squared_error',cv=5)
lasso_regressor.fit(X,y)

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.105636e+03, tolerance: 2.228e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.183199e+03, tolerance: 2.256e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.295536e+03, tolerance: 2.110e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.069544e+03, tolerance: 2.236e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.070127e+03, tolerance: 2.128e+00
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [ ]:
print(lasso_regressor.best_score_)      #here value of best score reduced  hence  use it
print(lasso_regressor.best_params_)

-0.5582759293868976
{'alpha': 0.001}

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train, y_test = train_test_split(
    X,y, test_size=0.33, random_state=42
)

In [ ]:
#linear regression with X_train and y_train

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

lin_reg=LinearRegression()
lin_reg.fit(X_train, y_train)
n_mse=cross_val_score(lin_reg,X_train,y_train,scoring = 'neg_mean_squared_error',cv=5)
print(n_mse)
mean_n_mse=np.mean(n_mse)
print(mean_n_mse)

# here as the value is going towards 0 ie it is a good improvement

[-0.54099828 -0.49871687 -0.50480739 -0.5200183  -0.55070903]
-0.5230499763383932

In [ ]:
# Ridge Regression with X_train and y_train
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
ridge=Ridge()

params={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20]}

ridge_regressor=GridSearchCV(ridge,params,scoring='neg_mean_squared_error',cv=5)
ridge_regressor.fit(X_train,y_train)

# here as the value is going towards 0 ie it is a good improvement

GridSearchCV(cv=5, estimator=Ridge(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [ ]:
# Lasso Regression with X_train and y_train
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV
lasso=Lasso()

params={'alpha':[1e-15,1e-10,1e-8,1e-3,1e-2,1,5,10,20]}

lasso_regressor=GridSearchCV(lasso,params,scoring='neg_mean_squared_error',cv=5)
lasso_regressor.fit(X,y)

c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.105636e+03, tolerance: 2.228e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.183199e+03, tolerance: 2.256e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.295536e+03, tolerance: 2.110e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.069544e+03, tolerance: 2.236e+00
  model = cd_fast.enet_coordinate_descent(
c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.070127e+03, tolerance: 2.128e+00
  model = cd_fast.enet_coordinate_descent(

GridSearchCV(cv=5, estimator=Lasso(),
             param_grid={'alpha': [1e-15, 1e-10, 1e-08, 0.001, 0.01, 1, 5, 10,
                                   20]},
             scoring='neg_mean_squared_error')

In [ ]:
y_pred = lasso_regressor.predict(X_test)
from sklearn.metrics import r2_score

r2_score_1 = r2_score(y_test , y_pred)
print(r2_score_1)

# its bad it should be near 1

0.3368861159176253

In [ ]:
y_pred = ridge_regressor.predict(X_test)
from sklearn.metrics import r2_score

r2_score_1 = r2_score(y_pred,y_test)
print(r2_score_1)

# its bad it should be near 1

0.33957429603867806

In [ ]:
y_pred = lin_reg.predict(X_test)
from sklearn.metrics import r2_score

r2_score_1 = r2_score(y_pred,y_test)
print(r2_score_1)

# its bad it should be near 1

0.3395742960386735

In [ ]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer

In [ ]:
df=load_breast_cancer()

# it should give us indep. features based on which we need to identify if person has cancer or not
X=pd.DataFrame(df['data'],columns=df['feature_names'])

In [ ]:
X.head()

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst radius,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [ ]:
# dependent feature
y = pd.DataFrame(df['target'] , columns=["Target"])
y

       Target
0       4.526
1       3.585
2       3.521
3       3.413
4       3.422
...       ...
20635   0.781
20636   0.771
20637   0.923
20638   0.847
20639   0.894

[20640 rows x 1 columns]

In [ ]:
## Train test spleit
from sklearn.model_selection import train_test_split
X_train, X_test ,y_train, y_test = train_test_split(
    X,y, test_size=0.33, random_state=42
)

In [ ]:
params = [{'C':[1,5,10]} , {'max_iter': [100,500]}]

In [ ]:
print(type(model1))
print(model1)

<class 'sklearn.linear_model._logistic.LogisticRegression'>
LogisticRegression(C=100)

In [ ]:
model1 = LogisticRegression(C=100,max_iter=100)

TypeError: 'Ridge' object is not callable

In [ ]:
model=GridSearchCV(model1,param_grid=params, scoring='r2',cv=5)
model.fit(X_train,y_train)

ValueError:
All the 25 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1403, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1469, in fit
    check_classification_targets(y)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "c:\Users\HP\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\multiclass.py", line 230, in check_classification_targets
    raise ValueError(
    ...<3 lines>...
    )
ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
model.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [ ]:
y_pred = model.predict(X_test)
y_pred

AttributeError: 'GridSearchCV' object has no attribute 'best_estimator_'

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report, accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred)

ValueError: continuous is not supported

In [ ]:
accuracy_score(y_test,y_pred)

ValueError: continuous is not supported

In [ ]:
print(classification_report(y_test,y_pred))